spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/qqhx_new?serverTimezone=UTC&useUnicode=ture&characterEncoding=utf-8&useSSL=TRUE
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  profile:
    active: dev

server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml,classpath:mapping/*/*Mapper.xml
  type-aliases-package: com.pengcheng.domain

#showSql
logging:
  level:
    com:
      pengcheng:
        dao: debug