spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/qqhx_new?serverTimezone=Asia/Shanghai&useUnicode=ture&characterEncoding=utf-8&useSSL=TRUE
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  profile:
    active: dev
  thymeleaf:
    cache: false        # 禁用缓存
    mode: LEGACYHTML5   # 非严格型检查 默认是html 严格检查

server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml,classpath:mapping/*/*Mapper.xml
  type-aliases-package: com.pengcheng.domain

#showSql
logging:
  level:
    com:
      pengcheng:
        dao: debug